GET https://cemacogt.vtexcommercestable.com.br/api/logistics/pvt/inventory/skus/1049542
X-VTEX-API-AppKey: vtexappkey-cemacogt-ALBDBH
X-VTEX-API-AppToken: DZHCKWRUCAOFUZFDNVSVQIAQMMZDQCLLKSSATEXUTTYICTCWBQJDSNIUZRPXWOEAPCVBGEKJYYCXKSNTKDBZSHSXKYBCOZXFOYSZYAPWGAFUKLKGDWNTMEHIKYRIDIUZ